apiVersion: v1
kind: Pod
metadata:
  name: cadvisor-agent
spec:
  containers:
    - name: cadvisor-agent
      image: google/cadvisor:0.19.3
      ports:
        - name: http
          containerPort: 8080
          hostPort: 4194
      volumeMounts:
        - name: varrun
          mountPath: /var/run
          readOnly: false
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        - name: sysfs
          mountPath: /sys
          readOnly: true
  volumes:
    - name: varrun
      source:
        hostDir:
          path: /var/run
    - name: varlibdocker
      source:
        hostDir:
          path: /var/lib/docker
    - name: sysfs
      source:
        hostDir:
          path: /sys
